name: Build ESP-AT Project

on: push

jobs:
  build-esp32-wroom-at:
    uses: ./.github/workflows/build_template_esp32.yml
    with:
      module_name: WROOM-32
      artifacts_name: esp32-wroom-at
    secrets: inherit
